name: Telegram Bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # обновлено с v2 до v4
      - name: Setup Python
        uses: actions/setup-python@v5  # обновлено с v2 до v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install telethon
      - name: Run bot
        env:
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
        run: python bot.py